export const GET_RECIPES_REQUEST = 'GET_RECIPES_REQUEST ';
export const GET_ALL_RECIPES_SUCCESS = 'GET_ALL_RECIPES_SUCCESS ';
export const GET_ALL_RECIPES_FAIL = 'GET_ALL_RECIPES_FAIL ';
export const GET_SINGLE_RECIPE_REQUEST = 'GET_SINGLE_RECIPE_REQUEST';
