// Recipe Types
export const GET_ALL_RECIPES_REQUEST = 'GET_ALL_RECIPES_REQUEST ';
export const GET_ALL_RECIPES_SUCCESS = 'GET_ALL_RECIPES_SUCCESS ';
export const GET_ALL_RECIPES_FAIL = 'GET_ALL_RECIPES_FAIL ';

export const GET_SINGLE_RECIPE_REQUEST = 'GET_SINGLE_RECIPE_REQUEST';
export const GET_SINGLE_RECIPE_SUCCESS = 'GET_SINGLE_RECIPE_SUCCESS';
export const GET_SINGLE_RECIPE_FAIL = 'GET_SINGLE_RECIPE_FAIL';

export const CREATE_RECIPE_REQUEST = 'CREATE_RECIPE_REQUEST';
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const CREATE_RECIPE_FAIL = 'CREATE_RECIPE_FAIL';

export const DELETE_RECIPE_REQUEST = 'DELETE_RECIPE_REQUEST';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_FAIL = 'DELETE_RECIPE_FAIL';

// User Types
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAIL = 'GET_USER_DATA_FAIL';

export const SET_USER_LOGGED_IN_ON_RELOAD = 'SET_USER_LOGGED_IN_ON_RELOAD';

export const GET_USER_RECIPES_REQUEST = 'GET_USER_RECIPES_REQUEST';
export const GET_USER_RECIPES_SUCCESS = 'GET_USER_RECIPES_SUCCESS';
export const GET_USER_RECIPES_FAIL = 'GET_USER_RECIPES_FAIL';
